### ISSUE TITLE
Routify intergration

### ISSUE THREAD

**Issue by sid3r** [dominikg/svite#11]
hello, thank you for the the amazing work, I need some help integrating [Routify](https://github.com/sveltech/routify). i have no idea where to start from since i dont understand how the different tools work together.

I forgot to mention, I'm using the _postcss-tailwind_ example.

**Comment by dominikg** [comment]
please check the routify-mdsvex example. if you need more help you can ask in routify or svite discord channels. 

closing. please follow the issue templates and do NOT post support requests here
