### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by jwrunner** [dominikg/svite#12]
## Description

I can't build my component and receive this error:
```Building for production...
[vite] Build errored out.
TypeError: Cannot read property 'includes' of undefined
    at /Users/jacobbowdoin/apps/elevation-pace-chart/node_modules/vite/dist/node/build/index.js:189:60
    at Array.findIndex (<anonymous>)
    at Object.build (/Users/jacobbowdoin/apps/elevation-pace-chart/node_modules/vite/dist/node/build/index.js:189:36)
    at async runBuild (/Users/jacobbowdoin/apps/elevation-pace-chart/node_modules/vite/dist/node/cli.js:174:9)```

## Reproduction

1. Download the minimal example
2. npm install
3. npm run build and see the error.

## Additional Information

- MacOS latest
  - node 12.16.3
  - npm 6.14.6
  - svite 0.2.3
  - vite v1.0.0-beta.12
  - svelte 3.24.0

**Comment by quantuminformation** [comment]
I also get an issue with the build from tailwind:

![image](https://user-images.githubusercontent.com/216566/87830192-dbf72e00-c880-11ea-8994-b0f2756c44d6.png)

this code isn't replaced with process vars

```js
module.exports = {
  purge: process.env.NODE_ENV === 'production' && {
    content: ['./src/**/*.svelte', './src/**/*.html', './src/**/*.css', './index.html'],
    options: {```

**Comment by quentincaffeino** [comment]
I'm experiencing same issue as @jwrunner. Tried with minimal and postcss-tailwind templates.

**Comment by dominikg** [comment]
it might be caused by a change in latest vite beta. please try with vite@1.0.0-beta.11

I'm not able to analyze this until monday

**Comment by quentincaffeino** [comment]
@dominikg, thanks, it worked.

**Comment by quangv** [comment]
Thanks @dominikg 

yeah `vite` [versions](https://www.npmjs.com/package/vite) `1.0.0-beta.12` and `1.0.0-rc.1` does not work atm...
