### ISSUE TITLE
Support importing uncompiled svelte packages

### ISSUE THREAD

**Issue by jamesopstad** [dominikg/svite#14]
**Describe the feature**
As far as I can tell, it's currently not possible to import an uncompiled svelte component from `node_modules`. This is supported by `rollup-plugin-svelte`, as described here - https://github.com/sveltejs/rollup-plugin-svelte#pkgsvelte.

**A Usecase**
This would allow users to avoid duplication of code and split projects into separate modules.

**Alternatives**
Importing the compiled components should work but this has disadvantages in a svelte project.

**Additional context**
For svelte packages, svite should import the uncompiled rather than the compiled source code if both are linked in the `package.json`.

**Comment by dominikg** [comment]
svite uses rollup-plugin-svelte(-hot) to build, so it should be supported in theory. I must admit that i did not try it until today.

I'm going to add examples for this soon. It would be great if you could let me know which library/component you're intending to use and maybe even some example code which demonstrates why it does not work.

**Comment by jamesopstad** [comment]
My use case is quite specific because I'm importing my own components using yarn workspaces. This should work if the more general use case is implemented though as it currently works with compiled components.

Importing a component such as this is a good example - https://www.npmjs.com/package/svelte-calendar. It doesn't provide a compiled version so won't work at present.

**Comment by dominikg** [comment]
I've created an example with svelte-calendar and renderless-svelte: https://github.com/dominikg/svite/tree/example-libraries
And another example with smelte: https://github.com/dominikg/svite/tree/example-smelte

`npm run dev` and `npm run build`  work on both.

I suspect this is an issue with yarn workspaces and resolving dependencies. 
I'm afraid i need a clean reproduction on this one to be able to help you. Please raise a bug report with the required information.

**Comment by jamesopstad** [comment]
I've just looked at the examples and you are using the full paths to import the components. This essentially bypasses the issue because the component code is not being located using the `svelte` entry in the component's `package.json`. This works of course, and also works fine with yarn workspaces, but the user shouldn't need to know the path to the component, only the package name.

**Comment by dominikg** [comment]
i added an enhancement for this. In your case using deep imports may be desirable, not sure if hmr works properly otherwise. (unless you do not intend to edit imported components)
