### ISSUE TITLE
State not maintained between HMRs

### ISSUE THREAD

**Issue by alexdilley** [dominikg/svite#16]
## Description

Reactive state not maintained during hot replacement.

## Reproduction

Using Svite template app (`yarn svite create svite-app`) as a basis, and mimicking Vite's own template app:

```html
<script>
  let count = 0;
</script>

<p>edit me</p>

<button on:click={() => count++}>count is: {count}</button>
```

`count` is not maintained between hot update.

## Additional Information

vite-plugin-svelte manages this – albeit only up to Vite `1.0.0-rc.1`, after which a change with Vite is breaking.

**Comment by dominikg** [comment]
You can enable internal state preservation with hot options when you configure svite plugin in vite config

`svite({hot:{noPreserveState: false}})` this is experimental and untested. please consult svelte-hmr docs and code 

Alternatively you chould consider moving state that should persist across hmr updates into separate stores, example: https://github.com/dominikg/svite/tree/master/examples/hmr-showcase

**Comment by alexdilley** [comment]
@dominikg thanks for your explanation.
