### ISSUE TITLE
HMR is broken in examples when using components

### ISSUE THREAD

**Issue by mgutz** [dominikg/svite#17]
## Description

After updating to latest, the minimal example and others do not hot update properly when updating an imported component.

The example (and my project) were working with vite betas.

## Reproduction

Start with `examples/minimal`

Create a `Hello.svelte` with content

```js
<sript>
export let name;
</script>

<h1>Hello {name}!</h1>
```

Use the component in `App.svelte`

```js
<script>
import Hello from './Hello.svelte'
</script>

<Hello name="Paddington" />
```

Run the server. On initial page load, everything works. Now edit `Hello.svelte` to use a different message say `<h1>Hello again {name}!</h1>`. The browser console 

```
Loading module from “http://localhost:3000/src/App.svelteimport=?t=1595460394958” was blocked because of a disallowed MIME type (“text/plain”). localhost:3000
Loading failed for the module with source “http://localhost:3000/src/App.svelteimport=?t=1595460394958”. localhost:3000:4:1
TypeError: error loading dynamically imported module client:67:17
    warnFailedFetch http://localhost:3000/vite/client:67
    updateModule http://localhost:3000/vite/client:285
[hmr] Failed to reload /src/App.svelteimport=. This could be due to syntax errors or importing non-existent modules. (see errors above) client:69:13
    warnFailedFetch http://localhost:3000/vite/client:69
    updateModule http://localhost:3000/vite/client:285
[vite]: js module hot updated:  /src/App.svelteimport= client:297:17

```

The browser is receiving the udpate but doesn't know what to do with it.

## Additional Information
macOS 10.15.4
svite 0.3.1
node: 12.18.2

**Comment by dominikg** [comment]
This seems to be caused by a change in vite.
For whatever reason, it generates code like this:
```js
import { createHotContext } from "/vite/client"; import.meta.hot = createHotContext("/src/Hello.svelteimport=");
``` 
I think there is a ? missing after Hello.svelte. Because of that the request for updated code goes to waste because the dev server isn't able to resolve Hello.svelteimport properly.

It does work with vite-1.0.0-beta.11. which generates
```js
import { createHotContext } from "/vite/hmr"; import.meta.hot = createHotContext("/src/Hello.svelte");
```
So until this is fixed i recommend to use vite-1.0.0-beta.11. 

I'm properbly going to turn vite into a svite dependency and pn the version until 1.0 is released.

**Comment by dominikg** [comment]
svite-0.4.0-beta.0 has been released which uses vite-1.0.0-rc.4 and hmr for children works correctly again.

You can create a beta project with `npx svite@beta create`    0.4.0 should follow shortly

**Comment by dominikg** [comment]
0.4.0 released.

**Comment by Kiho** [comment]
0.4.0 still not working for me, and dev dependency is pointing to ["vite": "1.0.0-beta.12"](https://github.com/dominikg/svite/blob/master/package.json#L89)

**Comment by dominikg** [comment]
thanks @Kiho .  with dev dependency updated to 1.0.0-rc4 i can confirm HMR is still broken.

**Comment by dominikg** [comment]
Well it is still broken, but the cause is different: vitejs/vite#662

A svite version that works around this issue is going to be released soon.

**Comment by Kiho** [comment]
It's working at my end, thanks for quick update.
