### ISSUE TITLE
Only onMount runs inside script on hmr

### ISSUE THREAD

**Issue by ImmanuelSamuel** [dominikg/svite#2]
First off awesome work with posting these template!

One issue I see is that only the code within the onMount function works. For example: I was using a d3 charting function outside the script ```plot(data)``` and call it inside onMount. Any changes made to the ```plot``` function is not reflected after save (hmr). However when I move the ```plot``` function inside the onMount function then changes made to the plot function is reflected. I understand that when the component is built the functions outside are run only once but this is not easy to for development testing. Coming from Vue the functions outside the mounted() function also gets updated so was expecting the same situation.

**Comment by dominikg** [comment]
Hi, thank you for reporting.

Do you have a repository or can you share a code example here to help me reproduce the issue?
Maybe @rixo has an idea whats happening.

**Comment by ImmanuelSamuel** [comment]
Please change the data to see if the plot updates

```
<script>
 import { onMount } from "svelte";
 import { select, selectAll, scaleLinear, axisBottom, axisLeft, csv } from "d3";

 let createAxes = (
  xlim = [0, 1],
  ylim = [0, 1],
  nxticks = 10,
  nyticks = 10
 ) => {
  var margin = { top: 30, right: 30, bottom: 30, left: 70 },
   width = 460 - margin.left - margin.right,
   height = 400 - margin.top - margin.bottom;

  // append the svg object to the body of the page
  var svg = select("#my_dataviz")
   .append("svg")
   .attr("width", width + margin.left + margin.right)
   .attr("height", height + margin.top + margin.bottom)
   .append("g")
   .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  //Read the data
  // Add X axis
  var x = scaleLinear().domain(xlim).range([0, width]);
  svg
   .append("g")
   .attr("transform", "translate(0," + height + ")")
   //  .style("color", "#000")
   .call(axisBottom(x).ticks(nxticks));

  // Add Y axis
  var y = scaleLinear().domain(ylim).range([height, 0]);
  svg.append("g").call(axisLeft(y).ticks(nyticks));
  return { svg, x, y };
 };
 let plot = (axes, data) => {
  // set the dimensions and margins of the graph
  let { svg, x, y } = axes;

  // Add dots
  svg
   .append("g")
   .selectAll("dot")
   .data(data)
   .enter()
   .append("circle")
   .attr("cx", function (d) {
    return x(d.x);
   })
   .attr("cy", function (d) {
    return y(d.y);
   })
   .attr("r", 7)
   .style("fill", "#69b3a2");
 };
 let data = [
  { x: 1, y: 1 },
  { x: 3, y: 2 },
  { x: 2, y: 1 },
 ];

 onMount(async () => {
  let axes = createAxes([0, 3], [0, 2], 5, 7);
  plot(axes, data);
 });
</script>

<div id="my_dataviz"></div>

<style>

</style>
```

**Comment by rixo** [comment]
The component is recreated on HMR and the whole script is reexecuted, but Svelte HMR preserves local state, that is all `let` vars, everything that Svelte sees as reactive. And so your previous value for data is conserved. If it is in onMount, it happens after HMR operations, so it does update the state and is visible.

You can use option noPreserveState to disable this behavior (@dominikg possible to pass HMR options in Svite?). Or you can add a `// @!hmr` comment somewhere in your code to disable it only for a given file (or temporarily, as long as the comment is there).

Totally need to document this. But where to write about this for it to be useful? What docs people read about HMR?

I am still not sure preservation of local state like this should be the default behavior... It's much less intuitive for users than the more destructive alternative. Any thought to share on this guys?

**Comment by dominikg** [comment]
yes, should work via vite.config.js
```js
const svite = require('svite');
const sviteConfig = {
  hot: {
    noPreserveState: true
  }
};
module.exports = {
  plugins: [svite(sviteConfig)],
};
```

**Comment by dominikg** [comment]
@ImmanuelSamuel please let me know if the above works for your case.

I'm considering using noPreserveState: true as default in svite. Also i am going to add some tests soon and more examples that demonstrate how hmr works with svelte components

**Comment by ImmanuelSamuel** [comment]
Yup that works! @dominikg The ```// @!hmr``` will be very useful as well.

**Comment by dominikg** [comment]
@ImmanuelSamuel 

I just released 0.0.10 with noPreserveState: true as default. If you prefer to use the `// @!hmr` comment, you can set it to false instead in vite.config.js

```js
const svite = require('svite');
module.exports = {
  plugins: [svite({ hot: { noPreserveState: false }})],
};
```

**Comment by dominikg** [comment]
fixed in 0.0.10.

**Comment by rixo** [comment]
I've documented the confusing behaviour [in svelte-hmr](https://github.com/rixo/svelte-hmr#preservation-of-local-state).

I'm still very split on the right default for this option, but I'm going to let it like it is, at least for now. My reasoning is that the feature is probably more discoverable if people search to disable it, whereas they might just think it's not available if it's not here.

@dominikg I don't want to force anything on your project, but I don't think we should have separate HMR defaults in different plugins.

**Comment by ImmanuelSamuel** [comment]
@rixo agreed I was thinking twice and just settled on putting everything within onMount. Glad I asked here.
