### ISSUE TITLE
ssr support

### ISSUE THREAD

**Issue by dominikg** [dominikg/svite#22]
vite has an --ssr option that is already enabled in svite, but the output is untested/not useful right now.

Check out how this can be used to enable ssr.

**Comment by benmccann** [comment]
It looks like Vite just created an SSR playground that might help with this: https://github.com/vitejs/vite/tree/main/packages/playground/ssr

**Comment by benmccann** [comment]
It looks like Vite just created an SSR playground that might help with this: https://github.com/vitejs/vite/tree/main/packages/playground/ssr

Here's a related ticket: https://github.com/vitejs/vite/issues/1290

**Comment by benmccann** [comment]
I tried it out, but it looks like we need a svelte plugin for Vite 2: https://github.com/rixo/svelte-hmr/issues/24#issuecomment-765162403

**Comment by aewing** [comment]
https://github.com/brillout/vite-plugin-ssr perhaps?

**Comment by benmccann** [comment]
New repo with ssr support at https://github.com/svitejs/svite
