### ISSUE TITLE
Importing routify decorators fails

### ISSUE THREAD

**Issue by rustybuddha** [dominikg/svite#27]
## Description
`  import { TabsTransition } from "@sveltech/routify/runtime/decorators";`
fails with:
`[vite] Failed to resolve module import "@sveltech/routify/runtime/decorators". (imported by /src/pages/example/transitions/tabs/_reset.svelte)`

## Reproduction
1. `npx svite create -t routify-mdsvex testing-svite`
2. copy example folder from routify-starter template
3. edit all imports from @sveltech/routify to @sveltech/routify/runtime to make them work in svite
4. start testing by `npm run dev`
5. open `localhost:3000/example/transitions/tabs/`
which will throw this error in command-line:
`[vite] Failed to resolve module import "@sveltech/routify/runtime/decorators". (imported by /src/pages/example/transitions/tabs/_reset.svelte)`
and the page won't load
6. edit src/pages/example/transitions/tabs/reset.svelte to import @sveltech/routify/decorators instead of @sveltech/routify/runtime/decorators, as it was originally on copying from starter template, also ends up splashing an error, but on the webpage itself, instead of on the command-line, and it is as follows:
Failed to init component
`TypeError: Cannot read property 'last' of null
    at Object.$$self.$$.update (http://localhost:3000/@modules/@sveltech/routify/runtime/decorators/BaseTransition.svelte?import:248:41)`

## Additional Information

- operating system Ubuntu based POP! OS
- versions for
  - node 12.16.3
  - npm 6.14.7
  - svite 0.3.1
  - vite ^1.0.0-rc.3
  - svelte ^3.24.0

**Comment by dominikg** [comment]
this is fixed in latest routify-mdsvex example, right?

**Comment by rustybuddha** [comment]
Yes. Yes it is. 
Just a note for anyone who wants to use decorators:
```javascript
import TabsTransition from "@sveltech/routify/runtime/decorators/TabsTransition.svelte";
```
or 
```javascript
import { TabsTransition } from "@sveltech/routify/decorators";
```
is the way to do it.

**Comment by dominikg** [comment]
Thanks.
