### ISSUE TITLE
[TS] Cannot import Types or Interfaces into svelte file

### ISSUE THREAD

**Issue by JustinVoitel** [dominikg/svite#35]
## Description
Importing a type or interface from a ts file under **src/** and using it throws a error in browser console: 
`Uncaught (in promise) SyntaxError: import not found: Layout`
Vite is obviously not including the export 

## Reproduction
1. clone repo and `npm i` examples/typescript/routify-mdsvex example
2. create **src/appstate.ts** with content: `export type LayoutMode = 'grid' | 'list'`
3. in **src/pages/index.svelte** replace all with:
```svelte
<script lang="ts">
  import { LayoutMode } from '../appstate';
  
  let test: LayoutMode = 'grid';
</script>

<p>layout: {test}</p>
```
4. `npm run dev`

## Additional Information

- operating system: Windows WSL 2
- versions for
  - node v14.4.0
  - npm 6.14.5
  - svite 0.4.1
  - vite 1.0.0-rc.4
  - svelte 3.24.0

**Comment by dominikg** [comment]
please try `import type ...`
