### ISSUE TITLE
svite dev cors

### ISSUE THREAD

**Issue by quentincaffeino** [dominikg/svite#36]
Add support for cors on svite dev

**Comment by dominikg** [comment]
Please follow the issue templates.
Also svite is the wrong repo for this. The dev server ist vite. In case you open a request there, again, please follow their templates and provide the information asked for.

Also check their docs if an existing vite feature might help you ( hint https://github.com/vitejs/vite#dev-server-proxy )

**Comment by quentincaffeino** [comment]
Sorry for bothering then. Thanks
