### ISSUE TITLE
svelte component library example/template

### ISSUE THREAD

**Issue by dominikg** [dominikg/svite#37]
**Describe the feature**
An example to be used as a template for create that creates a svelte component library project

**A Usecase**
The default svelte component library template is very basic.
Library developers would benefit from svite dx.

**Alternatives**
Leave it to the users to figure it out

**Additional context**
Think about commands.
- dev: serve component preview
- build: instead of an app build, build a package ready to be published on a registry

**Comment by lokhmakov** [comment]
For simple template enough that u already wrote.

## IMPROVMENTS:
— To preview components we can integrate Storybook in template
— Setup document system in template
— Setup plugins to control size of library. Research other popular ways to improve way how to dev libs
— Documentation for template (preparation for article):

- How to optimise work on library? (versioning, changelog, roadmap, commits, branches, PRs, feature requests, bug fix requests, contributors)
- Working with monorepos, multirepos, metarepos
- Styling recommendations

— Write article about `Best way to publish svelte components in 2020` (Increase svite popularity)

**Comment by Parables** [comment]
So I used Parcel for [Svelta](https://github.com/parables/svelta). But now that I have seen Svite, I will port the components to Vite. Does this close the issue?

**Comment by dominikg** [comment]
Hi @Parables ,

the goal of this enhancement is that you can do `npx svite create -t svelte-library my-svelte-lib` and have a project where you can build your own library.

Your work on svelta could serve as a starting point for the template. 

Of you have any questions, please ask away on discord
