### ISSUE TITLE
Please support  --mode in dev mode, to load data from .env.staging

### ISSUE THREAD

**Issue by quantuminformation** [dominikg/svite#42]
Its not possible to do this         `svite --mode staging --debug`

gives error: unknown option '--mode'

but you can do this        `svite build --mode staging --debug` and it will load variables from `.env.staging`

It would be nice to have the dev mode working too

For Vite docs see: https://github.com/vitejs/vite#modes-and-environment-variables

**Comment by dominikg** [comment]
added --mode option to `svite dev` command in svite 0.6.1-beta.1. Please try and let me know if it works for you.

**Comment by dominikg** [comment]
svite-0.6.1 has been released

**Comment by quantuminformation** [comment]
thanks mate, will test soon
