### ISSUE TITLE
Multiple rollup inputs

### ISSUE THREAD

**Issue by krevativ** [dominikg/svite#43]
**Describe the feature**
Make it possible to configure multiple inputs for rollup.

**A Usecase**
Rollup allows it to build [multiple bundles](https://rollupjs.org/guide/en/#configuration-files) from several different unrelated inputs at once. It would be great to have this option for code reuse.

**Comment by dominikg** [comment]
Hi,

thank you for your request. Could you please elaborate your usecase a little bit? Describe what kind of project you want to build, the directory structure you'd like to use and what output you expect.

Some general remarks:
Svite is vite plugin with an additional cli to make it easier to use. So it inherits most features but also limitations of vite. 
One requirement of vite is an index.html file in root, which is used as entry point for the build. Anything thats directly or indirectly imported from there is included automatically. While vite exposes options for additional rollup plugins via config, you cannot change the complete rollup config to add additional inputs etc.

**Comment by lokhmakov** [comment]
@krevativ 

I would go from the task to be solved.

For example, you can see in one of my repositories (svite-monorepo, branch evokme--ui) how to use a mono repository with shared code and svelte components.

It seems that to solve the problem of code reuse, especially in development mode, we no need multiple bundles.

And when we get to the problem of getting this code into production, we will look for a solution together.

**Comment by lokhmakov** [comment]
Also u can examine these two files:

https://github.com/lokhmakov/svite-monorepo/blob/evokeme--ui/apps/client/svite--exclude-shared.js

https://github.com/lokhmakov/svite-monorepo/blob/evokeme--ui/apps/client/vite.config.js

**Comment by krevativ** [comment]
Hi,

@dominikg sorry for the short description. You are right, vite would be probably a better place for this feature request, but I'm mainly interested in svelte, so I thought to write it here first. I didn't dive into the code and I hoped that this is somehow possible through the plugin system.

@lokhmakov thank you for your suggestions. Multiple production bundles are actually exactly what I want.

Let me describe it in a bit more detail.

When your project grows, you are likely to have multiple apps where you want to share some components. In this case you would need to choose between keeping everything in a monorepo and using tools like lerna or split the code into different repositories. There are some disadvantages to both options. And sadly most tools like vite, snowpack, create-react-app etc. don't offer an easy solution to this issue. I'd admit it's not very easy to solve, but I think it's possible. I have written something similar with webpack for react. In context of svelte this would look something like this:

 Project structure:
```bash
Root
    public
        build
            bundle1.js
            bundle2.js
         index.html
         index2.html
    src
        components
             comp.svelte
        apps
            app1.svelte
            app2.svelte
```
To build bundle1 and 2 for production, you would need to configure app1 and app2 as two distinct inputs. But vite encapsulates the rollup configuration, so you can't do that at the moment.

For development, it's almost the same. But at the start you would ask which app do you want to be watched for hmr or make it configurable. And all other apps are build just once and served as static files. It's rarely the case, where you need to watch multiple apps at once, so I think we can simply ignore this case.

I hope it's a bit more clear now what I'm trying to achieve?

**Comment by lokhmakov** [comment]
@krevativ It's branch special for you! )

https://github.com/lokhmakov/svite-monorepo/tree/krevativ

There u can find all benefits of monorepo and shared components and u can create any amount of applications and develop it fully separated. With production builds.

And video https://i.imgur.com/D9GmFmi.mp4

**Comment by dominikg** [comment]
@krevativ Thank you for expanding your usecase.

I second @lokhmakov with his suggestion of a mono-repo for this kind of situation. Imho a multi-input rollup build with a single src directory is not separating the different entities enough. 

svite-monorepo  is a great, thanks a lot for posting.

@krevativ please let us know if this works for you.

**Comment by krevativ** [comment]
Sorry for the late response.

@lokhmakov thank you for the repo and the video. So it's basically utilizes yarn workspaces?

@dominikg Well, this is well enough but it could be better. I see some problems too:

Pro:
  - yarn's workspaces make it easy to add local packages.
  - I can easily start multiple apps and watch for file changes.
  - monorepo

Con:
  - It makes you dependent on yarn (I have nothing against yarn in particular, but it's a disadvantage anyway)
  - Each app has its own node_modules folder with the same dependencies inside
  - Some config files must be duplicated and this can be annoying to keep them in sync
  - Some dependencies must be kept in sync too. For example, all apps will probably depend on the same svelte version.
  - I can't simply jump to definition in Visual Studio Code. (I have found the [Monorepo Workspace extension](https://dev.to/folke/monorepo-workspace-a-vs-code-extension-to-manage-monorepos-with-multi-root-workspaces-supports-lerna-yarn-pnpm-and-rush-1ki0) but this does not solve the problem)

**Comment by lokhmakov** [comment]
@krevativ Yep, yarn workspaces.

> It makes you dependent on yarn (I have nothing against yarn in particular, but it's a disadvantage anyway)

We using only yarn, bolt, lerna. All around yarn.

> Each app has its own node_modules folder with the same dependencies inside

Nope, only deps that differ in version.

> Some config files must be duplicated and this can be annoying to keep them in sync

Each application should have own configuration. It's usual case for deploy systems.

> Some dependencies must be kept in sync too. For example, all apps will probably depend on the same svelte version.

You can use bolt. That dont give chance to use diff versions of packages for all workspaces.

> I can't simply jump to definition in Visual Studio Code

Easy. Without any extension in `svite-monorepo` from apps/client that import {makeEntity} from @evoke-me/state I can jump to makeEntity in different package.

**Comment by krevativ** [comment]
> We using only yarn, bolt, lerna. All around yarn.

Never heard about bolt before. I will look at it. Thanks for the tip.

> Nope, only deps that differ in version.

You are right! I should have looked more carefully :) That's great!

> Each application should have own configuration. It's usual case for deploy systems.

Well, I think it depends. At work, we also have a monorepo and our config files are always the same. But I also see the advantage of it.

> Easy. Without any extension in `svite-monorepo` from apps/client that import {makeEntity} from @evoke-me/state I can jump to makeEntity in different package.

Strange, I can't. I'm on linux, and have VSC 1.49 and latest Svelte extension. And I can't jump. But I can jump to other component that is not in the workspace package. Do I have to set up yarn workspaces in VSC somehow?

**Comment by lokhmakov** [comment]
@krevativ 

> Strange, I can't. I'm on linux, and have VSC 1.49 and latest Svelte extension. And I can't jump. But I can jump to other component that is not in the workspace package. Do I have to set up yarn workspaces in VSC somehow?

I am talking about JS code in packages. For svelte components it should be full path. Or we should search some solution.

**Comment by lokhmakov** [comment]
Maybe just PR changes to vscode svelte `Go definition` code.

**Comment by krevativ** [comment]
@lokhmakov It doesn't work when I provide a full path too. I've also tried some other options but without success. So I've opened a new issue for the svelte VSC extension (https://github.com/sveltejs/language-tools/issues/537). Thank you for your help.

**Comment by dominikg** [comment]
Closing here as the original issue has been discussed in detail. If there is something else you want to suggest please open a new feature request.
