### ISSUE TITLE
Write some docs about commonjs packages

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#50]
_I opened this here: https://github.com/vitejs/vite/issues/813._

## Describe the bug

I'm trying to use [`flatpickr`](https://github.com/flatpickr/flatpickr) in a project where I'm already using Svite.

When I try to import a l10n file like this:

```js
import { French } from 'flatpickr/dist/l10n/fr.js'
```

[as suggested in docs for ES modules](https://flatpickr.js.org/localization/) then Vite is going crazy with this error:

```console
Uncaught (in promise) SyntaxError: The requested module '/@modules/flatpickr/dist/l10n/fr.js' does not provide an export named 'French'
```

I thinks we should write some docs about this because I know many people who have abandoned the use of this project (vite and svite) due to these problems which are not immediately addressable.

Can we write something about it?

## System Info

- **required** `vite` version: "vite": "1.0.0-rc.4" / "svite": "0.6.0"

**Comment by frederikhors** [comment]
They answered me here: https://github.com/vitejs/vite/issues/813#issuecomment-691799104.

Using docs here: https://github.com/dominikg/svite#custom-viteconfigjs, how can I write my custom `vite.config.js` just to fix this issue with flatpickr (and similar)?

Like this?

```js
module.exports = {
  optimizeDeps: {
    include: ['flatpickr/dist/l10n/it.js']
  }
}
```

Do I need this?

```js
module.exports = {
  // if you provite a svite plugin here, svite cli will use it instead of initializing one for you
  plugins: [svite(sviteConfig)],
  // if you don't use svite cli, you should provide rollupDedupe option, otherwise you risk duplicate svelte instances and errors
  rollupDedupe: ['svelte/animate', 'svelte/easing', 'svelte/internal', 'svelte/motion', 'svelte/store', 'svelte/transition', 'svelte'],
};
```

**Comment by dominikg** [comment]
vite.config.js
```js
module.exports = {
  optimizeDeps: {
    include: ['foo','bar']
  }
}
```
is the correct way to add additional dependencies to optimizeDeps. You don't have to setup svite yourself unless you want to use a custom sviteConfig in a file. 

flatpickr also just added support for use as esmodule https://github.com/flatpickr/flatpickr/pull/2046  so you might not even need to do that once thats released

**Comment by dominikg** [comment]
> I thinks we should write some docs about this because I know many people who have abandoned the use of this project (vite and svite) due to these problems which are not immediately addressable.
> Can we write something about it?

The very first sentence of vite README:

> Vite is an opinionated web dev build tool that serves your code via native ES Module imports during dev and bundles it with Rollup for production.

It's primary use is for es modules. If the way you or others are using commonjs modules is not supported by vite's optimizeDeps approach there's little svite can do about it. But you are right, maybe a warning about commonjs dependencies is in order. This has come up more than once.

**Comment by dominikg** [comment]
https://github.com/dominikg/svite#imports-of-commonjs-modules-dont-work-in-svite-dev
