### ISSUE TITLE
[vite] Optimizable dependencies detected

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#51]
**Describe the feature**

When I npm run dev Svite says to me:

```console
[vite] Optimizable dependencies detected:
svelte/animate, svelte/easing, svelte/internal, svelte/motion, svelte/store, svelte/transition, svelte, svelte-hmr/runtime/proxy-adapter-dom, svelte-hmr/runtime/hot-api-esm
```

Can you write something about it in docs?

**Comment by dominikg** [comment]
This is a message from vite. Svite is primarily a vite plugin with a cli addon to simplify setup. Users are expected to consult vite documentation where needed.
