### ISSUE TITLE
remove svite config "svelte" option

### ISSUE THREAD

**Issue by dominikg** [dominikg/svite#53]
**Describe the feature**
remove svite config "svelte" option in favor or svelte.config.js

**A Usecase**
Promote use of svelte.config.js
Reduce amount of options to keep documentation and api surface in check.

**Comment by jakobrosenberg** [comment]
Strong opponent of removing programmatic configuration here. 👋

As for promoting `svelte.config.js`, I think that's best handled through template layouts and documentation.
As for API surface, it shouldn't make much of a difference. The config object is the same regardless of how it's provided. 

Reasons to keep programmatic access to the config
1. Conventions. For good reason, libs like Rollup, Svelte, PostCSS, etc. all feature programmatic access to their configs. Some need static configs, some need dynamic.
2. Simplicity. If removed, there's very little simplicity gained for those who use a config file, but a lot lost for those who don't. This goes for both documentation and code.
3. Limitations. Plugins, extensions and frameworks which compile/modify configs in memory at runtime will no longer be able to use Svite. I know it's possible to write a `svelte.config.js` at runtime, but we're going down a dark path when we have to pass configs from function to function through a file. Especially if it involves overwriting config files in the root folder.

Removing a programmer's programmatic access to something as basic and fundamental as the config is IMHO counter productive. It introduces an array of issues and limitations to fix a non-issue.

Sorry if I came off a bit argumentative, but all my alarm bells are sounding off. 😅

**Comment by jakobrosenberg** [comment]
I'm currently testing out a Vite fork with exposed config parameter. If it checks out, I'll submit a PR to Vite. Would Svite be able to use the same logic?

Vite original
```javascript
export async function resolveConfig(
  mode: string,
  configPath?: string
): Promise<ResolvedConfig | undefined> {
  let config: ResolvedConfig | undefined

  // paraphrasing
  config = resolveConfig()
```

Vite with exposed config
```javascript
export async function resolveConfig(
  mode: string,
  configPath?: string,
  config?: ResolvedConfig | undefined
): Promise<ResolvedConfig | undefined> {

  if (!config){
    resolveConfig()
  }

```

As you can see, they're virtually identical. The only difference is the config is declared in the parameters instead of the function and the config resolve logic is put in a condition.

**Comment by dominikg** [comment]
I think there is a PR waiting for that in vite already: https://github.com/vitejs/vite/pull/740
also mentioned here https://github.com/vitejs/vite/issues/738.

I really hope vite starts releasing soon.
But rest assured svite won't remove the svelte option until where is a sufficient solution for your usecase.

**Comment by dominikg** [comment]
as said, svelte option stays. documentation will be improved eventually
