### ISSUE TITLE
mdsvex example error

### ISSUE THREAD

**Issue by goldcoders** [dominikg/svite#56]
Ive clone svite cd to examples/typescript/routify-mdsvex
yarn && yarn dev

it runs ok but when you visit the site , and click on link mdsvex
it wont show the page and a console error log this

```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:3000/src/pages/mdsvex.svx?import
```

**Comment by dominikg** [comment]
should be fixed in svite@0.7.1-beta.0 please try and let me know.
