### ISSUE TITLE
Move index.html in "public" dir from root

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#58]
**Describe the feature**
What do you think about having the `index.html` file in "public" instead of in the root like now?

I know that it is a file that is "processed" during the build phase but the root is perhaps not exactly the ideal space to keep it.

**Comment by dominikg** [comment]
The way it is now is because vite expects it to: https://github.com/dominikg/svite#project-setup

please contribute to the upstream issue about it: https://github.com/vitejs/vite/issues/798
