### ISSUE TITLE
Add "defer" to script in index.html or do not remove it

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#59]
**Describe the feature**

In my index.html I'm using

```html
<script defer type="module" src="/src/index.js"></script>
```

I think `defer` is valuable.

**What do you think about adding it?**

**Alternatives**
Alternatively can you please do not remove it when you change `src` value?

Thanks a lot for your work!

**Comment by dominikg** [comment]
no need for defer on `<script type="module">`. 
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

> There is no need to use the defer attribute (see <script> attributes) when loading a module script; modules are deferred automatically.

Also svite does not process index.html in any way. That's courtesy of vite.

**Comment by frederikhors** [comment]
Amazing thanks! :smile: ❤️
