### ISSUE TITLE
Add common eslint config to templates?

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#63]
**Describe the feature**
What do you think about adding a common standard eslint config in templates?

Maybe not in minimal, or maybe too.

**Comment by dominikg** [comment]
people have a lot of different opinions/expectations regarding eslint and settings and I want to keep the examples focussed on svite. no need to complicate things with more configs. 

An additional/separate example `eslint-prettier` could be added but i'm not convinced it adds value to svite. Did you experience any issues setting up eslint that warrant documentation/an example?

**Comment by frederikhors** [comment]
I agree. Sorry.
