### ISSUE TITLE
Validate script errors for Tailwind template

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#64]
## Description

Using for the first time typescript today.

After this: `npx svite create my-ts-project -t postcss-tailwind -ts`

and `npm run validate`

I have two errors:

```
src\App.svelte:16:3
Error: at-rule or selector expected (css)
```

and

```
src\App.svelte:15:26
Error: semi-colon expected (css)
```

**Comment by dominikg** [comment]
this is likely due to svelte-check not understanding tailwind `@apply`

**Comment by randyridge** [comment]
try `<style lang="postcss">@apply stuff here</style>`

**Comment by dominikg** [comment]
please check svite-0.8.0-beta.0. `npx svite@beta create -ts -t postcss-tailwind` it sets up postcss as default lang

**Comment by dominikg** [comment]
the examples now use @randyridge suggestion and validate returns without errors in svite 0.8.0.

Please note that postcss is not set up as default lang, you can do that but it comes with some disadvantages (eg it also defaults 3rd party library components to postcss).  So the recommended way is to specify it on each script/style node with lang attr
