### ISSUE TITLE
Typescript, cannot find name 'process' in index.ts

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#66]
**Describe the feature**

Using Typescript template if I use this code in index.ts:

```ts
if (process.env.NODE_ENV === 'production') {}
```

VSCode complain with:

`Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.ts(2591)`.

Why?

**Comment by frederikhors** [comment]
Maybe we need to add this?

```
"compilerOptions": {
    ...
    "types": ["node", "jest"]
  }
```

**Comment by dominikg** [comment]
vscode complains, but the code works. 

Adding the complete node types is wrong. If possible, you could add a custom type only containing process.env.NODE_ENV.

**Comment by randyridge** [comment]
looks like you'd want [import.meta.env.MODE](https://github.com/sveltejs/svelte-preprocess/issues/189) though I get a ts error that I ignore with a // @ts-ignore, same for import.meta.env.

**Comment by dominikg** [comment]
try this tsconfig:
```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "include": ["src/**/*"],
  "exclude": ["node_modules/*", "public/*"],
  "compilerOptions": {
    "module": "ESNext",
    "types": ["svelte","vite/dist/importMeta"]
  }
}
```

you should be able to use import.meta.env.MODE in place of process.env.NODE_ENV just fine.

**Comment by dominikg** [comment]
please try svite-0.8.0-beta.0 it adds above config. if you update an existing project please read notes in changelog

**Comment by codechips** [comment]
@dominikg what do you mean " it adds above config"? Where? I am having the same problem. TS + import.meta.env is giving me errors. It's actually the same in vitejs, but there you could solve it by doing  `import type {} from 'vite'`.

I solved it for now by copying Vite's d.ts file and putting it in `src/types.d.ts`.

```
declare interface ImportMeta {
  readonly hot?: {
    readonly data: any;

    accept(): void;
    accept(cb: (mod: any) => void): void;

    acceptDeps(dep: string, cb: (mod: any) => void): void;
    acceptDeps(deps: readonly string[], cb: (mods: any[]) => void): void;

    dispose(cb: (data: any) => void): void;
    decline(): void;
    invalidate(): void;

    on(event: string, cb: (...args: any[]) => void): void;
  };

  readonly env: {
    [key: string]: string | boolean | undefined;
    BASE_URL: string;
    MODE: string;
    DEV: boolean;
    PROD: boolean;
  };
}
```

**Comment by dominikg** [comment]
That looks like the type in `vite/dist/importMeta`. Your way works too, this is what i meant:
https://github.com/dominikg/svite/blob/beta/examples/typescript/minimal/tsconfig.json

you can try it locally with `npx svite@beta create -ts my-svite-beta-typescript-project`

**Comment by dominikg** [comment]
svite 0.8.0 has been released
