### ISSUE TITLE
Svelte components too?

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#67]
**Describe the feature**

What do you think about supporting Svelte components too?

**A Usecase**

It would be amazing to have autogenerated typings.

Thanks again for your amazing work!

**Comment by dominikg** [comment]
There is an open enhancement issue about a svelte component example here: https://github.com/dominikg/svite/issues/37
Please contribute there or elaborate more here if you have something different in mind.

**Comment by frederikhors** [comment]
Oh wow! Thanks.
