### ISSUE TITLE
Scriptable svite builds

### ISSUE THREAD

**Issue by ImmanuelSamuel** [dominikg/svite#7]
How could we have a scriptable build so as to change the 'src' directory to something else with different config eg: noPreserveState: True based on variables.

**Comment by dominikg** [comment]
svite is a vite plugin, so it comes down to using vite cli options.

you could use a combination of -c and root.

vite help
```
Commands:
  vite                       Start server in current directory.
  vite serve [root=cwd]      Start server in target directory.
  vite build [root=cwd]      Build target directory.
Options:
  --config, -c               [string]  use specified config file
```

Please note that `noPreserveState: true` is default in svite since version 0.1.0

I'm not entirely sure what your goal is but if you need help with setting it up, please share some code and more details what you want to do. If it is something cool and useful, consider writing an example and i'll add it to the examples in svite :)

Thank you for trying svite :+1:

**Comment by ImmanuelSamuel** [comment]
I was trying to do something like the following:
```
const { build } = require("vite");
const svite = require("svite");

let b = async () => {
 const result = await build({
  plugins: [svite],
  base: "/stats/pwlr",
  outDir: "./dist/stats/pwlr",
 });
};

b();
```
But I am running into error that says vite needs plugin to load non-js files. I am nto sure if include svite the way it is currently included is the right way.

**Comment by dominikg** [comment]
try
```js
const { build } = require("vite");
const svite = require("svite");

let b = async () => {
 const result = await build({
  plugins: [svite({/*...your svite options here...*/})],
  root: "./src1",
  base: "./dist",
  outDir: "./dist/stats",
 });
};

b();
```

**Comment by ImmanuelSamuel** [comment]
I am still getting the following error.
```(node:3640) UnhandledPromiseRejectionWarning: Error: Unexpected token (Note that you need plugins to import files 
that are not JavaScript)```
The goal is the following. Building multiple src directories into separate dist folders with different base paths so that these can be accessed in different routes.

**Comment by dominikg** [comment]
Do you have a link to a repo? A more complete error message would also help. Right now i don't have much to work with.

Also i'm not sure i understand your idea correctly. 
Building multiple spa's and combining the result into a static serve sounds very complicated.
Wouldn't it make more sense to build a single spa with a router, add an export script that crawls a locally served build and save the crawl result?

**Comment by ImmanuelSamuel** [comment]
I will try to get a repo going but the only addition is the script above to the root dir. Yeah the crawler would work but would it handle dynamic on click imports?

**Comment by jakobrosenberg** [comment]
@ImmanuelSamuel is this related to your issue?

https://github.com/vitejs/vite/pull/464

**Comment by dominikg** [comment]
You did not provide additional information. 

If you need help with scripting vite, please ask at the appropriate support channel for vite. I'm keeping this issue tracker focussed on issues with svite itself.

/closed
