### ISSUE TITLE
Live example for examples to assist testing with Edge 44

### ISSUE THREAD

**Issue by quantuminformation** [dominikg/svite#75]
**Describe the feature**
Live example for https://github.com/dominikg/svite/tree/master/examples/postcss-tailwind
**A Usecase**
For testing on various virtual machines
**Alternatives**
downloading repo and setting it up on vm
**Additional context**
Having issues with example cloned from postcss-tailwind on MS edge 44 (default non chromium version on win 10)

**Comment by dominikg** [comment]
As you already posted on discord
es2015 flag is needed for non-chromium edge support: https://github.com/vitejs/vite#browser-support

But i believe chromium based version has been default for quite a while (note the Version number above 80):
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

**Comment by quantuminformation** [comment]
Its the default windows bundles that still come with 44 by default.
