### ISSUE TITLE
error TS2688: Cannot find type definition file for 'vite/dist/importMeta'.

### ISSUE THREAD

**Issue by corbaz** [dominikg/svite#78]
## Description

svelte-check && tsc --noEmit

## Reproduction

svelte-check found 0 errors, 0 warnings and 0 hints
error TS2688: Cannot find type definition file for 'vite/dist/importMeta'.

Found 1 error.

## Additional Information

Windows 10 x64

**Comment by dominikg** [comment]
which package manager are you using? pnpm or yarn2 may have put vite in a place where tsc doesn't see it. you can try to add vite as a devDependency or copy the importMeta.d.ts from vite into your project

**Comment by corbaz** [comment]
pnpm

**Comment by dominikg** [comment]
@corbaz does `pnpm i -D vite` solve your issue?
