### ISSUE TITLE
Problem with routify template

### ISSUE THREAD

**Issue by thomanimation** [dominikg/svite#79]
## Description

Running the routify-mdsvex template results in an empty page and an error about missing .routify/routes

## Reproduction

Run:  ```svite create -t routify-mdsvex```
and then: ```svite dev``` inside the newly created folder: /svite-routify-mdsvex
Open the browser  at http://localhost:3000/
See an empty page and check the console for the error.

**Comment by dominikg** [comment]
please use `npm run dev` routify needs a separate process to watch for route changes. the run script starts it alongside the vite server

**Comment by thomanimation** [comment]
Thank you very much.

Στις Πέμ, 29 Οκτ 2020, 8:31 μ.μ. ο χρήστης Dominik G. <
notifications@github.com> έγραψε:
