### ISSUE TITLE
[Question] Difference between svite and vite-plugin-svelte

### ISSUE THREAD

**Issue by kwangure** [dominikg/svite#8]
Is HMR the only difference between [`vite-plugin-svelte`](https://github.com/intrnl/vite-plugin-svelte) and `svite`? I haven't used much of either, but I haven't spotted any other significant differences.

cc @intrnl

**Comment by dominikg** [comment]
Actually hmr (made possible by the awesome @rixo with svelte-hmr) is about the only similarity between svite and vite-plugin svelte.

I figure this question may come up a lot, so here's a comparison, based largely on my own work and opinion. @intrnl, if you feel i made any unfair conclusions or want to add to this list, you know where to find me :>

|Feature| svite (0.2.0) | vite-plugin-svelte (1.4.0) |  personal opinion |
| --- | --- | --- | --- |
| dev transform|  uses rollup-plugin-svelte-hot   |  uses svelte compiler and svelte-hmr   | svite works for all svelte preprocessors, vite-plugin-svelte lacks custom extension support (eg. mdsvex .svx) |
| dev optimizations | has a cache to avoid compiling unchanged sources again   |  -  | svites approach uses a workaround, but i made a [PR for vite](https://github.com/vitejs/vite/pull/510) that will enable a clean implementation |
| build | uses rollup-plugin-svelte-hot | relies on vite using transform from dev | svite builds optimized for production, vite-plugin-svelte always compiles with 'dev: true' |
| config | supports svelte.config.js and has opinonated defaults | you can pass options via vite plugin options | svite requires less effort to get running and allows more control
| documentation |  [readme](https://github.com/dominikg/svite#svite), [examples](https://github.com/dominikg/svite/tree/master/examples) |[readme](https://github.com/intrnl/vite-plugin-svelte#vite-plugin-svelte) |  svite's documentation needs improvement, buts its a lot more than what vite-plugin-svelte has to offer|
| test | has [tests](https://github.com/dominikg/svite/tree/master/test) | - |  vite is far from mature. tests help with stability and catching compatibility issues early |
| logging | has a custom logger that prints svelte compiler warnings during dev/build |  ? |  feedback to the user is important |
| benchmark | [check this out](https://github.com/dominikg/svite/issues/6) | - | yeah, that one doesn't count. it's still cool though and you can easily modify it to use vite-plugin-svelte |
| package manager support | has only been tested with npm | known to work with pnpm  and yarn | consider vite-plugin-svelte if you value pnpm support over other features mentioned here

**Comment by intrnl** [comment]
I've continued maintaining my plugin because I wanted a simple integration for Svelte components and nothing more, and I think that's the real difference between the two.

**Comment by kwangure** [comment]
> I wanted a simple integration for Svelte components and nothing more

@intrnl, what aspects of Svite are _non-simple_ for your current workflow? Can they be fixed with a PR?

I hope this is not presumptuous. My concern here was unnecessarily dividing the Svelte community.

**Comment by dominikg** [comment]
I have updated the table above with a 'goal'  line that includes @intrnl  statement.

I don't think 2 vite plugins with different goals are dividing the svelte community. This is so niche right now that people interested in this are going to be doing research anyways and this issue should clear things up.

That being said i'm more than open to contributions.

**Comment by rixo** [comment]
Don't worry, having 2 Vite plugins won't divide the Svelte community.

It's not the same thing contributing to a project and controlling it. It's fine if they want to explore each their own way.

**Comment by dominikg** [comment]
I try to not have open issues dangling and feel the initial question has been sufficiently answered so i'm closing this for now. Feel free to reopen if anything is missing.
