### ISSUE TITLE
Error: "No client callback was registered"

### ISSUE THREAD

**Issue by cp-sean** [dominikg/svite#9]
## Description

Possible conflict with `page` router. Upon saving, error.

## Reproduction

Too complex to easily create a code snippet.

## Additional Information

On initial load, page renders correctly with no errors. Upon edit and save, I get this error:
`[vite] got js update notification for "/src/pages/Welcome.svelte" but no client callback was registered. Something is wrong.`

**Comment by dominikg** [comment]
Too complex to access with the information provided.
